#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if ! echo "$branch" | grep -Eq "^(feat|bug|chore|docs|refactor|test|fix)/"; then
  echo "❌ Error: Branch name must start with feat/, bug/, chore/, docs/, refactor/, test/, or fix/."
  exit 1
fi
